# Generated by Django 5.2 on 2025-05-05 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadgen_id', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('custom_fields', models.JSONField(default=dict)),
                ('gpt_score', models.FloatField(default=0.0)),
                ('gpt_reason', models.TextField(blank=True)),
                ('total_score', models.FloatField(default=0.0)),
                ('is_spam', models.BooleanField(default=False)),
                ('is_valid_email', models.BooleanField(default=False)),
                ('is_valid_phone', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='FacebookPageConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=100, unique=True)),
                ('page_name', models.CharField(max_length=255)),
                ('page_access_token', models.TextField()),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facebook Page Connection',
                'verbose_name_plural': 'Facebook Page Connections',
                'ordering': ['-connected_at'],
            },
        ),
        migrations.CreateModel(
            name='GmailCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_uri', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('scopes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeadRoutingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to_gmail', models.BooleanField(default=False)),
                ('spam_labeling_enabled', models.BooleanField(default=True)),
                ('good_lead_subject', models.CharField(default='New Lead', max_length=100)),
                ('spam_lead_subject', models.CharField(default='Spam Lead', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_routing_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hubspot_access_token', models.TextField(blank=True, null=True)),
                ('hubspot_refresh_token', models.TextField(blank=True, null=True)),
                ('pipedrive_access_token', models.TextField(blank=True, null=True)),
                ('pipedrive_refresh_token', models.TextField(blank=True, null=True)),
                ('pipedrive_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('lead_filter_count', models.IntegerField(default=0)),
                ('lead_filter_quota', models.IntegerField(default=0)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_status', models.CharField(default='inactive', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('send_non_spam', models.BooleanField(default=True)),
                ('send_spam', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
