# Generated by Django 5.2 on 2025-04-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebooklead',
            name='score',
        ),
        migrations.AddField(
            model_name='facebooklead',
            name='gpt_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facebooklead',
            name='gpt_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='facebooklead',
            name='total_score',
            field=models.FloatField(default=0.0),
        ),
    ]
