# Generated by Django 5.2 on 2025-04-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_facebooklead_score_facebooklead_gpt_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebooklead',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='facebooklead',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
