# Generated by Django 5.2 on 2025-04-21 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_facebooklead_custom_fields_facebooklead_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebooklead',
            options={'ordering': ['-received_at']},
        ),
        migrations.AddField(
            model_name='facebooklead',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facebooklead',
            name='custom_fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='facebooklead',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='facebooklead',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='facebooklead',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facebooklead',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
