# Generated by Django 5.2 on 2025-04-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_facebooklead_options_facebooklead_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebooklead',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
