# Generated by Django 5.2 on 2025-04-21 04:40

from django.db import migrations

def associate_leads_with_superuser(apps, schema_editor):
    # Get the historical models
    FacebookLead = apps.get_model('leads', 'FacebookLead')
    User = apps.get_model('auth', 'User')
    
    # Get the first superuser, or create one if none exists
    superuser = User.objects.filter(is_superuser=True).first()
    if not superuser:
        superuser = User.objects.create_superuser(
            username='admin',
            email='admin@example.com',
            password='adminpassword123'
        )
    
    # Update all leads that don't have a user
    FacebookLead.objects.filter(user__isnull=True).update(user=superuser)

def reverse_leads_association(apps, schema_editor):
    # Get the historical model
    FacebookLead = apps.get_model('leads', 'FacebookLead')
    # Set all leads' user to None
    FacebookLead.objects.all().update(user=None)

class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_facebooklead_message'),
    ]

    operations = [
        migrations.RunPython(
            associate_leads_with_superuser,
            reverse_leads_association
        ),
    ]
