# Generated by Django 5.2 on 2025-05-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_price_userprofile_zoho_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ghl_api_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
