# Generated by Django 5.2 on 2025-05-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_userprofile_ghl_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadroutingsettings',
            name='advanced_filters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
