# Generated by Django 5.2 on 2025-05-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_leadroutingsettings_advanced_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebooklead',
            name='is_filtered_out',
            field=models.BooleanField(default=False),
        ),
    ]
