# Generated by Django 5.2 on 2025-05-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_leadroutingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadroutingsettings',
            name='good_lead_subject',
            field=models.CharField(default='New Lead', max_length=100),
        ),
        migrations.AddField(
            model_name='leadroutingsettings',
            name='spam_lead_subject',
            field=models.CharField(default='Spam Lead', max_length=100),
        ),
    ]
