# Generated by Django 5.2 on 2025-05-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_webhooksettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebooklead',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
