# Generated by Django 5.2 on 2025-05-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_alter_facebooklead_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pipedrive_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pipedrive_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pipedrive_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
