# Generated by Django 5.2 on 2025-05-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_remove_userprofile_lead_filter_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lead_filter_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lead_filter_quota',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_status',
            field=models.CharField(default='inactive', max_length=50),
        ),
    ]
