from django.urls import path, reverse_lazy
from . import views
from . import views_pipedrive
from leads.views_stripe import create_checkout_session, subscription_success, subscription_cancel, stripe_webhook, cancel_subscription, billing_portal
from leads.views_hubspot import hubspot_connect, hubspot_callback, hubspot_connected_success, hubspot_disconnect
from leads.views import integrations_view
from django.contrib.auth import views as auth_views
from leads.views_salesforce import salesforce_connect, salesforce_callback, salesforce_disconnect
from leads.views_zoho import zoho_connect, zoho_callback, zoho_disconnect

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('dashboard/', views.lead_dashboard, name='dashboard'),
    path('facebook/webhook/', views.facebook_webhook, name='webhook'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('facebook/connect/', views.facebook_connect, name='facebook_connect'),
    path('facebook/callback/', views.facebook_callback, name='facebook_callback'),
    path('facebook/select-page/', views.select_facebook_page, name='select_facebook_page'),
    path('facebook/save-page/', views.save_facebook_page, name='save_facebook_page'),
    path('connected-pages/', views.connected_pages_view, name='connected_pages'),
    path('connected-pages/disconnect/<str:page_id>/', views.disconnect_page_view, name='disconnect_page'),
    path('connected-pages/conflict/<str:page_id>/', views.handle_page_conflict, name='page_conflict'),
    path('leads/<int:pk>/', views.lead_detail_view, name='lead_detail'),
    path('leads/<int:pk>/toggle-spam/', views.toggle_lead_spam, name='toggle_lead_spam'),
    path('leads/export/', views.export_clean_leads, name='export_clean_leads'),
    path('privacy/', views.privacy_policy, name='privacy_policy'),
    path('terms/', views.terms_of_service, name='terms_of_service'),
    path('about/', views.about_view, name='about'),
    path('create-checkout-session/', create_checkout_session, name='create_checkout_session'),
    path('subscription/success/', subscription_success, name='subscription_success'),
    path('subscription/cancel/', subscription_cancel, name='subscription_cancel'),
    path('pricing/', views.pricing_view, name='pricing'),
    path('hubspot/connect/', hubspot_connect, name='hubspot_connect'),
    path('hubspot/callback/', hubspot_callback, name='hubspot_callback'),
    path('hubspot/connected/', hubspot_connected_success, name='hubspot_connected_success'),
    path('hubspot/disconnect/', hubspot_disconnect, name='hubspot_disconnect'),
    path('integrations/', integrations_view, name='integrations'),
    path('settings/lead-routing/', views.lead_routing_settings_view, name='lead_routing_settings'),
    path('settings/email/', views.update_email_view, name='update_email'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset_form.html',
        email_template_name='registration/password_reset_email.html',
        success_url=reverse_lazy('leads:password_reset_done'),
    ), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='leads/password_reset_done.html',
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='leads/password_reset_confirm.html',
        success_url=reverse_lazy('leads:password_reset_complete'),
    ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='leads/password_reset_complete.html',
    ), name='password_reset_complete'),
    path('settings/webhook/', views.webhook_settings_view, name='webhook_settings'),
    path('settings/webhook/test/', views.test_webhook, name='test_webhook'),
    path('validate-phone/', views.validate_phone_view, name='validate_phone'),
    path('pipedrive/connect/', views_pipedrive.pipedrive_connect, name='pipedrive_connect'),
    path('pipedrive/callback/', views_pipedrive.pipedrive_callback, name='pipedrive_callback'),
    path('pipedrive/disconnect/', views_pipedrive.pipedrive_disconnect, name='pipedrive_disconnect'),
    path('stripe/webhook/', stripe_webhook, name='stripe_webhook'),
    path('subscription/cancel-manual/', cancel_subscription, name='cancel_subscription'),
    path('billing-portal/', billing_portal, name='billing_portal'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('settings/lead-routing/how-to-folder/', views.how_to_folder_view, name='how_to_folder'),
    path('settings/lead-routing/how-to-inbox/', views.how_to_inbox_view, name='how_to_inbox'),
    path('solutions/', views.solutions_view, name='solutions'),
    path('salesforce/connect/', salesforce_connect, name='salesforce_connect'),
    path('salesforce/callback/', salesforce_callback, name='salesforce_callback'),
    path('salesforce/disconnect/', salesforce_disconnect, name='salesforce_disconnect'),
    path('zoho/connect/', zoho_connect, name='zoho_connect'),
    path('zoho/callback/', zoho_callback, name='zoho_callback'),
    path('zoho/disconnect/', zoho_disconnect, name='zoho_disconnect'),
    path('ghl/settings/', views.ghl_settings_view, name='ghl_settings'),
    path('ghl/disconnect/', views.ghl_disconnect, name='ghl_disconnect'),
    path('settings/', views.settings_view, name='settings'),
    path('send-to-crm/<int:lead_id>/', views.send_to_crm_view, name='send_to_crm'),
    path('settings/subscription/', views.subscription_management_view, name='subscription_management'),
    path('solutions/fake-leads/', views.solution_fake_leads, name='solution_fake_leads'),
    path('solutions/high-quality-leads/', views.solution_high_quality_leads, name='solution_high_quality_leads'),
    path('solutions/clean-leads/', views.solution_clean_leads, name='solution_clean_leads'),
    path('solutions/crm-clean/', views.solution_crm_clean, name='solution_crm_clean'),
] 